### ISSUE TITLE
robin-language.org is 404 ?

### ISSUE THREAD

**Issue by juner** [robin-language/robin#18]
https://robin-language.org/
is 404.

**Comment by effse7en** [comment]
Robin was owned by Softomotive, who got bought by Microsoft in 2020.

https://powerautomate.microsoft.com/en-us/blog/microsoft-acquires-softomotive-to-expand-low-code-robotic-process-automation-capabilities-in-microsoft-power-automate/

Robin is abandonware at this point.

**Comment by juner** [comment]
@effse7en thank you.
