### ISSUE TITLE
AppMask Control Not Working

### ISSUE THREAD

**Issue by pravesh2891** [robin-language/robin#4]
Hi,
I tried giving the Element/Control post capturing the Control from AppMask bt the same are not working when i execute the code.
Attaching the screenshots for reference.
Any help would be appreciated.
Thanks,
Pravesh 
![17-10-2019 11-39-08](https://user-images.githubusercontent.com/49717236/66982663-44d42e80-f0d4-11e9-8f7b-72951572bd24.png)
![17-10-2019 11-41-00](https://user-images.githubusercontent.com/49717236/66982669-49004c00-f0d4-11e9-9b38-32e4812fd377.png)
![17-10-2019 11-46-01](https://user-images.githubusercontent.com/49717236/66982678-4c93d300-f0d4-11e9-8b3d-5cd57f015479.png)
![17-10-2019 11-46-35](https://user-images.githubusercontent.com/49717236/66982684-4f8ec380-f0d4-11e9-827f-2806a2d1ce53.png)
![17-10-2019 11-47-58](https://user-images.githubusercontent.com/49717236/66982689-53224a80-f0d4-11e9-8d21-f5c2c847337d.png)

**Comment by jpapadimitriou** [comment]
@pravesh2891 You are getting these kind of errors because of wrong syntax in your commands.
To be more specific: 
1) **Calc** issue: your "`Set Selsec`" should be 

`Set Selsec to Calc.CalcMaskApp.Window_Calculator.Button_Seven` 
Note that you shouldn't use quotes.

2) **Browser** issue: the mindset is the same as before. 
Command on line 9 should be:
..... `Control: BrowserGoogle.ClickMask.Screeeen2.valueeees`
Again without quotes. 
Note that you are also including `Screeeen1` in your path, but this is invalid.

**Comment by pravesh2891** [comment]
Hi James,
Tried the resolution provided by you but i am still getting the errors below.
Please refer the attachments.
Please help in the above issue
![18-10-2019 09-38-31](https://user-images.githubusercontent.com/49717236/67065388-c0dd7d80-f18b-11e9-91f0-14c68b7dbf98.png)
![18-10-2019 09-41-42](https://user-images.githubusercontent.com/49717236/67065396-c5a23180-f18b-11e9-8788-a13adc291e24.png)


Thanks,
Pravesh

**Comment by pravesh2891** [comment]
Also please let me know how you figured out that  'Calc' and 'BrowserGoogle' need to get appended in the beginning.

**Comment by jpapadimitriou** [comment]
Hi @pravesh2891,

There is either something wrong with the path or the .appmask was modified externally. Did you interfere with it after extracting the element?

Regarding the **Calc** and **BrowserGoogle**, please check here:
https://robin-language.org/docs/robin-the-rpa-language/controls-repository-appmask/#the-appmask-file

Best regards,
J.

**Comment by pravesh2891** [comment]
Hi James,
I have created **new .appmask and .Robin file** and this for Internet Explorer Click is working fine.
However for Calculator i am getting error below.
Pl
![18-10-2019 14-05-00](https://user-images.githubusercontent.com/49717236/67081481-de730d00-f1b4-11e9-8134-e993e8226631.png)
![18-10-2019 14-06-18](https://user-images.githubusercontent.com/49717236/67081493-e337c100-f1b4-11e9-8209-327d0f8f4f72.png)

ease help in the above issue.
Thanks,
Pravesh

**Comment by jpapadimitriou** [comment]
@pravesh2891 
Currently the `.GetWindow` action is not fully functional. 
We are working towards its completion. 
As soon as we release the new version of Robin all the changes/fixes will be available in the changelog that will be published on GitHub. :)

Best regards,
J.

**Comment by pravesh2891** [comment]
Hi James,
Does it mean that we have to wait fro Desktop Automation till Get Window gets fixed?
Also can you please suggest how to give new line break in the script.

**Comment by jpapadimitriou** [comment]
@pravesh2891, please elaborate what do you mean with Desktop Automation.
Also regarding syntax please read the official docs and regarding any guidance or questions make sure to use the official [Robin forum](https://forum.robin-language.org/).
Please only post issues/bugs here. 
Thanks.

Best regards,
J.

**Comment by jpapadimitriou** [comment]
I am closing the thread since it doesn't account for a validated issue/bug.
