### ISSUE TITLE
Issue with connecting to terminal emulator for mainframe

### ISSUE THREAD

**Issue by sethulekshmik** [robin-language/robin#5]
When trying to connect to mainframe emulator (IBM PCOM) from Robin editor using OpenSession command, the following occurred.
 "L1:0	Error communicating with the emulator ".

The command used in Robin command editor for connection is as below.
"TerminalEmulation.OpenSession HllapiPath:'C:\Program Files (x86)\IBM\Personal Communications\EHLAPI32.dll' SessionName:'SessionA' Session=>Terminalsession".

Could not find any debugging help instructions in any site. Please help.

Sethu.

**Comment by jpapadimitriou** [comment]
Hello @sethulekshmik, 

I have tried to connect to IBM PCOMM using the `OpenSession` action. 
Everything worked fine. 
Please try re-writing your command by replacing 'SessionA' with just 'A' in the SessionName property input.

Best regards, 
J.

**Comment by jpapadimitriou** [comment]
I am closing the thread for now since it isn't validated as an issue.

**Comment by sethulekshmik** [comment]
Thanks. The above solution worked for me.

**Comment by jpapadimitriou** [comment]
Happy to hear that @sethulekshmik .
For future questions please use the [official forum](https://forum.robin-language.org/).
Also feel free to post your suggestions and/or POCs there.

Best regards,
J.
