### ISSUE TITLE
Problem loading robot

### ISSUE THREAD

**Issue by Code4FunVienna** [robin-language/robin#8]
I just installed Robin on two maschines and run the same code with Robin. 
On the first it runs like a charm
On the second it gives me 'Problem loading robot'

Is there a log file where I can find the reason for this error?
What setting are required to make Robin load the robot on my second maschine?

I found the forum post about this topic: https://forum.robin-language.org/t/problem-loading-robot-while-executing-script/215/11

So I changed the firewall settings for all exe, I set 'Run as admin' for all exe
Unfortunately it did not help.

I found out that my problem is with launching a browser
WebAutomation.LaunchFirefox Url: "https://news.orf.at" \
                            WindowState: WebAutomation.BrowserWindowState.Maximized \
                            BrowserInstance=> Browser

As soon as I add this command to the script the 'Problem loading robot' will occur.

Please help.
Thank you.

**Comment by jpapadimitriou** [comment]
@Code4FunVienna this was not a Robin issue but an access rights issue as you stated here:
https://forum.robin-language.org/t/problem-loading-robot-while-executing-script/215/27

Best regards,
J.
